name: Todo app CI
# 1. 언제 실행할 것인가?
on:
  push:
    branches: [ "develop", "master" ] # 브랜치 이름
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:29.1.3-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
      # 2. 소스 코드 체크아웃
      - uses: actions/checkout@v4

      # 자바 버전 23
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'gradle' # 캐싱 추가 , 빌드 시간 감소

      # 4. Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. 빌드 및 테스트 실행
      - name: Build with Gradle
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          DOCKER_HOST: tcp://localhost:2375
          DOCKER_TLS_VERIFY: "0"
        run: ./gradlew build -Dspring.profiles.active=test

      # 도커 빌드 및 푸시 단계 추가
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # 도커 이미지 빌드 및 푸시
      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-app:latest

      - name: Deploy to GCP
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key : ${{ secrets.GCP_SSH_KEY }}
          script: |
            # 기존 컨테이너 중지 및 삭제
            docker rm -f my-todo-app || true
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
            
            docker run -d \
              --name my-todo-app \
              --network host \
              -e PASS_WORD=${{ secrets.DB_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
            
            docker image prune -f