name: Todo app CI
# 1. 언제 실행할 것인가?
on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 2. 소스 코드 체크아웃
      - uses: actions/checkout@v4

      # 3. Java 17 설정 (프로젝트 자바 버전에 맞게 수정하세요)
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # 4. Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. 빌드 및 테스트 실행
      - name: Build with Gradle
        run: ./gradlew build