name: Todo app CI
# 1. 언제 실행할 것인가?
on:
  push:
    branches: [ "develop", "master" ] # 브랜치 이름
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 2. 소스 코드 체크아웃
      - uses: actions/checkout@v4

      # 자바 버전 23
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'gradle' # 캐싱 추가 , 빌드 시간 감소

      # 4. Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. 빌드 및 테스트 실행
      - name: Build with Gradle
        run: ./gradlew build